[[module]]
loaded_before = ["overworld"]

# Here is the configuration file of the game resources, which defines the paths of various animations and sprites.
# Each resource has a unique name and corresponding file path for easy reference in game code.
# For animation resources, horizontal flipping (flip_x) and vertical flipping (flip_y) are turned off by default.
# And looping is enabled by default.
# These can be set as needed.

# --characters--
# -flowey-
[[animations]]
name = "flowey_idle"
path = "assets/textures/overworld/characters/flowey/idle"

[[animations]]
name = "flowey_sink"
path = "assets/textures/overworld/characters/flowey/sink"

# -frisk-
# walk
[[animations]]
name = "frisk_idle_down"
path = "assets/textures/overworld/characters/frisk/walk/down/0.png"

[[animations]]
name = "frisk_idle_left"
path = "assets/textures/overworld/characters/frisk/walk/side/0.png"

[[animations]]
name = "frisk_idle_right"
path = "assets/textures/overworld/characters/frisk/walk/side/0.png"
flip_x = true

[[animations]]
name = "frisk_idle_up"
path = "assets/textures/overworld/characters/frisk/walk/up/0.png"
# walk
[[animations]]
name = "frisk_walk_down"
path = "assets/textures/overworld/characters/frisk/walk/down"

[[animations]]
name = "frisk_walk_left"
path = "assets/textures/overworld/characters/frisk/walk/side"

[[animations]]
name = "frisk_walk_right"
path = "assets/textures/overworld/characters/frisk/walk/side"
flip_x = true

[[animations]]
name = "frisk_walk_up"
path = "assets/textures/overworld/characters/frisk/walk/up"
#frame_duration = 0.10

# run
[[animations]]
name = "frisk_run_down"
path = "assets/textures/overworld/characters/frisk/run/down"

[[animations]]
name = "frisk_run_left"
path = "assets/textures/overworld/characters/frisk/run/side"

[[animations]]
name = "frisk_run_right"
path = "assets/textures/overworld/characters/frisk/run/side"
flip_x = true

[[animations]]
name = "frisk_run_up"
path = "assets/textures/overworld/characters/frisk/run/up"

# -toriel-
[[animations]]
name = "toriel_walk_down"
path = "assets/textures/overworld/characters/toriel/walk/down"

[[animations]]
name = "toriel_walk_left"
path = "assets/textures/overworld/characters/toriel/walk/side"
flip_x = true

[[animations]]
name = "toriel_walk_right"
path = "assets/textures/overworld/characters/toriel/walk/side"

[[animations]]
name = "toriel_walk_up"
path = "assets/textures/overworld/characters/toriel/walk/up"

# -objects-
# everywhere
[[sprites]]
name = "chest_box"
path = "assets/textures/overworld/objects/everywhere/chestbox.png"

[[animations]]
name = "save_point"
path = "assets/textures/overworld/objects/everywhere/savepoint"